server:
  address: 52.5.255.36
  port: '8082'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sun
    url: jdbc:mysql://my_mysql_container:3306/sunboard?serverTimezone=UTC&characterEncoding=UTF-8
    password: '1234'
  redis:
    host: 52.5.255.36
    port: 6379
    password: 1234



# mybatis 관련 설정
mybatis:
  # resources/mapper/ 에 있는 모든 xml 파일
  mapper-locations: mapper/*.xml